---
driver:
  name: vagrant
  network:
    forwarded_port:
      guest: 9090
      host: 9090
      auto_correct: true

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: windows-2012r2

suites:
  - name: windows
    run_list:
      - recipe[openfire::default]
    includes: windows-2012r2
  - name: centos
    run_list:
      - recipe[openfire::default]
      - recipe[kitchen_sudoers::default]
    includes: [centos-6, centos-7]
