---
driver:
  name: vagrant
  network:
    forwarded_port:
      guest: 9090
      host: 9090
      auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list: apt
  - name: debian-7.7
    run_list: apt
  - name: centos-6.4
#  - name: fedora-20

suites:
  - name: default
    run_list: openfire::default
    attributes:
      postgresql:
        password:
          postgres: 'somepassword'
      openfire:
        database:
            type: 'postgresql'
            password: 'anotherpassword'

  - name: embedded_db
    run_list: openfire::default
    attributes:
      openfire:

  - name: package
    run_list: openfire::package
    attributes:
      openfire:

