---
driver:
  name: vagrant
  network:
    forwarded_port:
      guest: 9090
      host: 9090
      auto_correct: true
    forwarded_port:
      guest: 9091
      host: 9091
      auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.7
  - name: centos-6.4

suites:
  - name: default
    run_list: openfire::default
    attributes:
      postgresql:
        password:
          postgres: 
      openfire:
        database:
            type: 'postgresql'
            password: 'anotherpassword'

  - name: embedded_db
    run_list: openfire::default
    attributes:
      openfire:



